version: '3'

services:
  webserver:
    build: ./nginx
    ports:
      - "8082:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - php-app

  app:
    build: ./php
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    networks:
      - php-app
  
  db:
     build: ./mysql
     restart: always
     ports:
      - 3307:3306
     env_file:
      - ./mysql/.env
    #  environment:
    #   MYSQL_ROOT_PASSWORD: root_password
    #   MYSQL_DATABASE: laravue_docker
    #   MYSQL_USER: docker
    #   MYSQL_PASSWORD: docker_pass
     volumes:
      - mysql_app_data:/var/lib/mysql
     networks:
       - php-app

volumes:
  mysql_app_data:

networks:
  php-app: